### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by biojppm** [mymindstorm/setup-emsdk#28]
When the action runs, Github issues this warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mymindstorm/setup-emsdk@v11

**Comment by mmoskal** [comment]
@mymindstorm could this be merged and tagged? right now I have semantic-release build failing since it doesn't like node14 being installed via setup-emsdk

**Comment by mymindstorm** [comment]
Thanks for the ping @mmoskal , I've not had much time for open-source work due to life changes a year or two ago. 

I've pushed v12 via ed0d39adca709d0c4f7253f52a73759b7694a5f8, which should resolve this issue. Although, I still need to go and update `@actions/*` and `ava`. Please let me know if that resolves the issues with y'alls repos.

**Comment by mmoskal** [comment]
Thank you!

It looks like the node 14.18.2 is installed by emsdk install script itself not the action. We were able to work around the issue by running setup-node action (with node 18) after setup-emsdk and before semantic-release
